# Generated by Django 3.2 on 2021-04-27 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210426_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='commit',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
    ]
