# Generated by Django 3.2 on 2021-04-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210427_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='commit',
            new_name='body',
        ),
    ]
